framework:
    validation:
        email_validation_mode: html5
        not_compromised_password: true
        enable_annotations: true


when@test:
    framework:
        validation:
            not_compromised_password: false
