name: PHP Code Style Fixer

on:
  workflow_run:
    workflows: [ "Set Up Env" ]
  push:
    branches:
      - 'feature/**'

jobs:
  check-psr-compatibility:
    runs-on: ubuntu-latest

    steps:
      - uses: StephaneBour/actions-php-cs-fixer@8.1
      with:
        path: ./src
