name: PHP Code Style Fixer

on:
  workflow_run:
    workflows: [ "Set Up Env" ]
  push:
    branches:
      - 'develop'
      - 'feature/**'

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga